language: perl
perl:
  - "5.8"
  - "5.8-thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20-thr"
  - "5.22-thr"
  - "5.24-thr"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - cpan-install Test2
notifications:
  slack:
    rooms:
      - perl-test2:kI7LQjG4iRjIqA2JTl770A5F#general
    on_success: change

