skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl -y
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm

build_script:
  - perl -e 2

test_script:
  - dzil test

